[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
via_ir = true
optimizer = true
optimizer_runs = 1000000
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.production]
via_ir = true
optimizer = true
optimizer_runs = 1000000

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
celo-alfajores = "wss://alfajores-forno.celo-testnet.org/ws"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
celo-alfajores = { key = "${CELOSCAN_API_KEY}" }